directories:
  output: release
  buildResources: assets
appId: com.mtlabs.rcdigital.profitmakerpos
productName: Profit Maker POS
artifactName: ProfitMakerPOS-${version}-${platform}-${arch}.${ext}
publish:
  - provider: github
    owner: MTZ-Profit-maker-2-6v
    repo: Smart-Pos
files:
  - filter:
      - dist/**
      - electron/**
win:
  target:
    - nsis
  icon: build/icon.ico
  requestedExecutionLevel: highestAvailable
mac:
  target:
    - dmg
    - zip
electronVersion: 27.3.11
